export const martketOptions = [
  {
    id: 1,
    market: 'US',
    quoteCurrency: 'USD',
  },
  {
    id: 2,
    market: 'HK',
    quoteCurrency: 'HKD',
  },
  {
    id: 3,
    market: 'AT',
    quoteCurrency: 'AUD',
  },
  {
    id: 4,
    market: 'CA',
    quoteCurrency: 'CAD',
  },
  {
    id: 5,
    market: 'JT',
    quoteCurrency: 'JPY',
  },
  {
    id: 6,
    market: 'EU',
    quoteCurrency: 'EUR',
  },
  {
    id: 7,
    market: 'NZ',
    quoteCurrency: 'NZD',
  },
  {
    id: 8,
    market: 'SP',
    quoteCurrency: 'SGD',
  },
  {
    id: 9,
    market: 'CH',
    quoteCurrency: 'CNY',
  },
  {
    id: 10,
    market: 'LN',
    quoteCurrency: 'GBP',
  },
  {
    id: 11,
    market: 'GY',
    quoteCurrency: 'EUR',
  },
  {
    id: 12,
    market: 'FP',
    quoteCurrency: 'EUR',
  },
].map(item => ({text: item.market, value: item.market}))

export const data = {
  pageIndex: 1,
  pageSize: 30,
  totalPage: 201,
  totalCount: 6025,
  pageDatas: [
    {
      id: 6089,
      code: 'TAL US 06/18/21 C32.5 Equity',
      name: 'TAL US 06/18/21 C32.5 Equity',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2021-07-21 18:29:20',
      createUser: 'admin',
      nameEn: 'TAL US 06/18/21 C32.5 Equity',
      codeExchange: 'TAL US 06/18/21 C32.5 Equity',
      codeBloomberg: 'TAL US 06/18/21 C32.5 Equity',
      isinCode: 'TAL US 06/18/21 C32.5 Equity',
      idStr: '6089',
    },
    {
      id: 6088,
      code: 'lvmh',
      name: 'lvmh',
      market: 'EU',
      quoteCurrency: 'EUR',
      desc: '',
      type: 2,
      createTime: '2021-06-25 17:57:59',
      createUser: 'admin',
      nameEn: 'lvmh',
      codeExchange: 'lvmh',
      codeBloomberg: 'lvmh',
      isinCode: '',
      idStr: '6088',
    },
    {
      id: 6087,
      code: 'XAU',
      name: 'XAU',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2021-05-12 15:14:53',
      createUser: 'admin',
      nameEn: 'XAU',
      codeExchange: 'XAU',
      codeBloomberg: 'XAUUSD Curncy',
      isinCode: '',
      idStr: '6087',
    },
    {
      id: 3088,
      code: 'DDD',
      name: 'DDD SP Equity',
      market: 'SP',
      quoteCurrency: 'SGD',
      desc: '',
      type: 2,
      createTime: '2021-04-29 09:44:57',
      createUser: 'admin',
      nameEn: 'DDD SP Equity',
      codeExchange: 'DDD',
      codeBloomberg: 'DDD SP Equity',
      isinCode: 'DDD001',
      idStr: '3088',
    },
    {
      id: 3087,
      code: 'CCC',
      name: 'CCC SP Equity',
      market: 'SP',
      quoteCurrency: 'SGD',
      desc: '',
      type: 2,
      createTime: '2021-04-29 09:35:51',
      createUser: 'admin',
      nameEn: 'CCC SP Equity',
      codeExchange: 'CCC',
      codeBloomberg: 'CCC SP Equity',
      isinCode: '11',
      idStr: '3087',
    },
    {
      id: 3086,
      code: 'BBB',
      name: 'BBB SP Equity',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2021-04-29 09:49:00',
      createUser: 'admin',
      nameEn: 'BBB SP Equity',
      codeExchange: 'BBB',
      codeBloomberg: 'BBB SP Equity',
      isinCode: '0',
      idStr: '3086',
    },
    {
      id: 3085,
      code: 'AAA',
      name: 'AAA SP Equity',
      market: 'SP',
      quoteCurrency: 'SGD',
      desc: '',
      type: 2,
      createTime: '2021-04-25 15:10:33',
      createUser: 'admin',
      nameEn: 'AAA SP Equity',
      codeExchange: 'AAA',
      codeBloomberg: 'AAA SP Equity',
      isinCode: 'AAA',
      idStr: '3085',
    },
    {
      id: 3084,
      code: 'TEST',
      name: 'TEST SP Equity',
      market: 'AT',
      quoteCurrency: 'AUD',
      desc: '',
      type: 2,
      createTime: '2021-04-25 09:37:23',
      createUser: 'admin',
      nameEn: 'TEST',
      codeExchange: 'TEST',
      codeBloomberg: 'TEST SP Equity',
      isinCode: 'TEST00999',
      idStr: '3084',
    },
    {
      id: 3083,
      code: 'MCT',
      name: 'MCT SP Equity',
      market: 'SP',
      quoteCurrency: 'SGD',
      desc: '',
      type: 2,
      createTime: '2021-06-21 19:07:39',
      createUser: 'admin',
      nameEn: 'MCT',
      codeExchange: 'MCT',
      codeBloomberg: 'MCT SP Equity',
      isinCode: '',
      idStr: '3083',
    },
    {
      id: 3080,
      code: '122',
      name: '农业主题',
      market: 'HK',
      quoteCurrency: 'HKD',
      desc: '',
      type: 2,
      createTime: '2021-03-08 14:22:21',
      createUser: 'admin',
      nameEn: 'nong',
      codeExchange: '00122',
      codeBloomberg: '122 HK Equity',
      isinCode: 'HK0122000687',
      idStr: '3080',
    },
    {
      id: 3078,
      code: '3347',
      name: '泰格医药',
      market: 'HK',
      quoteCurrency: 'HKD',
      desc: '',
      type: 2,
      createTime: '2021-01-26 10:54:57',
      createUser: 'admin',
      nameEn: 'taigeyiyao',
      codeExchange: '03347',
      codeBloomberg: '3347 HK Equity',
      isinCode: 'CNE1000040M1',
      idStr: '3078',
    },
    {
      id: 3077,
      code: 'SIE',
      name: '西门子',
      market: 'GY',
      quoteCurrency: 'EUR',
      desc: '',
      type: 2,
      createTime: '2020-08-25 10:15:34',
      createUser: 'admin',
      nameEn: 'SIEMENS',
      codeExchange: 'SIE',
      codeBloomberg: 'SIE GY Equity',
      isinCode: '',
      idStr: '3077',
    },
    {
      id: 3076,
      code: 'VOW',
      name: 'VOLKSWAGEN AG',
      market: 'GY',
      quoteCurrency: 'EUR',
      desc: '',
      type: 2,
      createTime: '2020-08-25 10:15:34',
      createUser: 'admin',
      nameEn: 'VOLKSWAGEN AG',
      codeExchange: 'VOW',
      codeBloomberg: 'VOW GY Equity',
      isinCode: '',
      idStr: '3076',
    },
    {
      id: 3075,
      code: 'PCRFY',
      name: '松下电器',
      market: 'JT',
      quoteCurrency: 'JPY',
      desc: '',
      type: 2,
      createTime: '2020-08-25 09:19:21',
      createUser: 'admin',
      nameEn: 'Panasonic',
      codeExchange: 'PCRFY',
      codeBloomberg: 'PCRFY JP Equity',
      isinCode: '',
      idStr: '3075',
    },
    {
      id: 3074,
      code: '9988',
      name: '阿里巴巴',
      market: 'HK',
      quoteCurrency: 'HKD',
      desc: '',
      type: 2,
      createTime: '2020-08-24 18:01:10',
      createUser: 'admin',
      nameEn: 'Alibaba',
      codeExchange: '09988',
      codeBloomberg: '9988 HK Equity',
      isinCode: 'KYG017191142',
      idStr: '3074',
    },
    {
      id: 3073,
      code: '9999',
      name: '网易',
      market: 'HK',
      quoteCurrency: 'HKD',
      desc: '',
      type: 2,
      createTime: '2020-07-29 14:25:28',
      createUser: 'admin',
      nameEn: 'Netease',
      codeExchange: '09999',
      codeBloomberg: '9999 HK Equity',
      isinCode: 'KYG6427A1022',
      idStr: '3073',
    },
    {
      id: 3072,
      code: 'BLCT',
      name: '蓝城兄弟',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-07-15 14:05:19',
      createUser: 'admin',
      nameEn: 'Blued',
      codeExchange: 'BLCT',
      codeBloomberg: 'BLCT US Equity',
      isinCode: 'US09610L1061',
      idStr: '3072',
    },
    {
      id: 3071,
      code: '763',
      name: '中兴通讯',
      market: 'HK',
      quoteCurrency: 'HKD',
      desc: '',
      type: 2,
      createTime: '2020-07-15 10:22:42',
      createUser: 'admin',
      nameEn: 'Zhongxin',
      codeExchange: '00763',
      codeBloomberg: '763 HK Equity',
      isinCode: 'CNE1000004Y2',
      idStr: '3071',
    },
    {
      id: 3070,
      code: 'XP',
      name: 'xp',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-12-15 17:44:23',
      createUser: 'admin',
      nameEn: 'xxp1',
      codeExchange: 'XP02',
      codeBloomberg: 'XP US Equity',
      isinCode: 'KYG982391099',
      idStr: '3070',
    },
    {
      id: 3069,
      code: 'XXXL',
      name: '加大码衣服',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-06-15 17:08:43',
      createUser: 'admin',
      nameEn: 'XXXL',
      codeExchange: 'XXXL',
      codeBloomberg: 'XXXL US Equity',
      isinCode: '',
      idStr: '3069',
    },
    {
      id: 3068,
      code: 'WTT',
      name: 'WTT',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-06-11 14:23:52',
      createUser: 'admin',
      nameEn: 'WTT',
      codeExchange: 'WTT',
      codeBloomberg: 'WTT',
      isinCode: 'US9765241081',
      idStr: '3068',
    },
    {
      id: 3067,
      code: 'ASML',
      name: '阿麦斯公司',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-06-11 12:05:02',
      createUser: 'admin',
      nameEn: 'ASML Holding',
      codeExchange: 'ASML',
      codeBloomberg: 'ASML US Equity',
      isinCode: 'USN070592100',
      idStr: '3067',
    },
    {
      id: 33,
      code: 'AMD',
      name: '美国超微公司',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-06-12 18:29:06',
      createUser: 'admin',
      nameEn: 'Advanced Micro Decices Inc',
      codeExchange: 'AMD',
      codeBloomberg: 'AMD US Equity',
      isinCode: 'US0079031078',
      idStr: '33',
    },
    {
      id: 35,
      code: 'QD',
      name: '趣店',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-06-12 18:29:06',
      createUser: 'admin',
      nameEn: 'Qudian Inc',
      codeExchange: 'QD',
      codeBloomberg: 'QD US Equity',
      isinCode: 'US7477981069',
      idStr: '35',
    },
    {
      id: 34,
      code: 'SQ',
      name: 'Square',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-06-12 18:29:06',
      createUser: 'admin',
      nameEn: 'Square Inc',
      codeExchange: 'SQ',
      codeBloomberg: 'SQ US Equity',
      isinCode: 'US8522341036',
      idStr: '34',
    },
    {
      id: 6,
      code: 'BABA',
      name: '阿里巴巴',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-04-17 15:44:22',
      createUser: 'admin',
      nameEn: 'Alibaba Group Holding Ltd',
      codeExchange: 'BABA',
      codeBloomberg: 'BABA US Equity',
      isinCode: 'US01609W1027',
      idStr: '6',
    },
    {
      id: 7,
      code: 'AMZN',
      name: '亚马逊',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-04-17 15:44:22',
      createUser: 'admin',
      nameEn: 'Amazon.com Inc',
      codeExchange: 'AMZN',
      codeBloomberg: 'AMZN US Equity',
      isinCode: 'US0231351067',
      idStr: '7',
    },
    {
      id: 8,
      code: 'NFLX',
      name: '奈飞',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-04-17 15:44:22',
      createUser: 'admin',
      nameEn: 'Netflix Inc',
      codeExchange: 'NFLX',
      codeBloomberg: 'NFLX US Equity',
      isinCode: 'US64110L1061',
      idStr: '8',
    },
    {
      id: 9,
      code: 'MSFT',
      name: '微软',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-04-17 15:44:22',
      createUser: 'admin',
      nameEn: 'Microsoft',
      codeExchange: 'MSFT',
      codeBloomberg: 'MSFT US Equity',
      isinCode: '',
      idStr: '9',
    },
    {
      id: 10,
      code: 'AAPL',
      name: '苹果',
      market: 'US',
      quoteCurrency: 'USD',
      desc: '',
      type: 2,
      createTime: '2020-04-17 15:44:22',
      createUser: 'admin',
      nameEn: 'Apple Inc',
      codeExchange: 'AAPL',
      codeBloomberg: 'AAPL US Equity',
      isinCode: 'US0378331005',
      idStr: '10',
    },
  ],
}
