export const dictionary = {
  language_code: 'zh_CN',
  info_type: {
    description: '资讯类型',
    tags: [
      {
        id: 1,
        description: '盘前简报',
      },
      {
        id: 2,
        description: '周度脉搏',
      },
      {
        id: 3,
        description: '华港要评',
      },
      {
        id: 4,
        description: '结构化产品',
      },
      {
        id: 5,
        description: '银行信息',
      },
      {
        id: 6,
        description: '金融街亮点',
      },
      {
        id: 7,
        description: '市场动态',
      },
      {
        id: 8,
        description: 'Wall Street Highlights',
      },
      {
        id: 9,
        description: '债券周报',
      },
      {
        id: 10,
        description: '市场快讯',
      },
      {
        id: 11,
        description: '投行视角',
      },
      {
        id: 12,
        description: '私募要闻',
      },
      {
        id: 13,
        description: '私行视角',
      },
    ],
  },
  target: {
    description: '面向对象',
    tags: [
      {
        id: 1,
        description: '华港科技APP',
      },
      {
        id: 2,
        description: '金马分销平台',
      },
      {
        id: 3,
        description: '华港CRM后台',
      },
    ],
  },
  language: {
    description: '文章语言',
    tags: [
      {
        id: 1,
        description: '中文',
      },
      {
        id: 2,
        description: '英文',
      },
    ],
  },
  market: {
    description: '市场',
    tags: [
      {
        id: 1,
        description: '中国内地',
      },
      {
        id: 2,
        description: '中国香港',
      },
      {
        id: 3,
        description: '美国',
      },
      {
        id: 4,
        description: '亚太',
      },
      {
        id: 5,
        description: '欧洲',
      },
    ],
  },
  asset: {
    description: '大类资产',
    tags: [
      {
        id: 1,
        description: '股票',
      },
      {
        id: 2,
        description: '债券',
      },
      {
        id: 3,
        description: '外汇',
      },
      {
        id: 4,
        description: '大宗商品',
      },
      {
        id: 5,
        description: '另类投资',
      },
      {
        id: 6,
        description: '宏观',
      },
    ],
  },
  industry: {
    description: '行业主题',
    tags: [
      {
        id: 1,
        description: '互联网信息服务',
      },
      {
        id: 2,
        description: '新能源汽车',
      },
      {
        id: 3,
        description: '互联网零售',
      },
      {
        id: 4,
        description: '手机硬件',
      },
      {
        id: 5,
        description: '传统汽车',
      },
      {
        id: 6,
        description: '新媒体',
      },
      {
        id: 7,
        description: '芯片',
      },
      {
        id: 8,
        description: '消费',
      },
      {
        id: 9,
        description: '金融',
      },
      {
        id: 10,
        description: '工业',
      },
      {
        id: 11,
        description: '能源',
      },
      {
        id: 12,
        description: '教育',
      },
      {
        id: 13,
        description: '生物医药',
      },
      {
        id: 14,
        description: '博彩',
      },
      {
        id: 15,
        description: '原材料',
      },
      {
        id: 16,
        description: '公共事业',
      },
    ],
  },
}

export const newsListData = {
  page: null,
  pageIndex: 1,
  pageSize: 50,
  totalPage: 10,
  totalCount: 457,
  pageDatas: [
    {
      id: 667,
      title: '437878',
      image: '',
      publishTime: 1629685651000,
      publisher: 'Jack',
      source: '',
      digest: '54667',
      keywords: '["11"]',
      isOutside: 1,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 3,
      isOriginal: 1,
      newsType: 1,
      desc: '54667',
      keywordsList: ['11'],
      accountId: 10000004,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 666,
      title: 'aapl资讯测试',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/a4cb6040-fea6-4144-aeec-5a5b8956764eblob.png',
      publishTime: 1629450570000,
      publisher: 'Jeff',
      source: '',
      digest: 'aaPL资讯测试',
      keywords: '["8"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 0,
      objectType: 3,
      isOriginal: 1,
      newsType: 1,
      desc: 'aaPL资讯测试',
      keywordsList: ['8'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 665,
      title: '关联标的全局搜索测试',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/f7bb35f3-261a-4a34-a909-88610bc01259blob.png',
      publishTime: 1629426071000,
      publisher: 'Jeff',
      source: '',
      digest: '关联标的全局搜索测试关联标的全局搜索测试',
      keywords: '["23"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 4,
      objectType: 1,
      isOriginal: 1,
      newsType: 1,
      desc: '关联标的全局搜索测试关联标的全局搜索测试',
      keywordsList: ['23'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: 8,
          institutionId: null,
          code: 'NFLX',
          codeExchange: 'NFLX',
          codeBloomberg: 'NFLX US Equity',
          nameEn: 'Netflix Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '奈飞',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 7,
          institutionId: null,
          code: 'AMZN',
          codeExchange: 'AMZN',
          codeBloomberg: 'AMZN US Equity',
          nameEn: 'Amazon.com Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '亚马逊',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 63,
          institutionId: null,
          code: '1288',
          codeExchange: '01288',
          codeBloomberg: '1288 HK Equity',
          nameEn: 'Agricultural Bank of China Ltd',
          lastPrice: '',
          riseFallPer: '',
          name: '农业银行',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 64,
          institutionId: null,
          code: '941',
          codeExchange: '00941',
          codeBloomberg: '941 HK Equity',
          nameEn: 'China Mobile Ltd',
          lastPrice: '',
          riseFallPer: '',
          name: '中国移动',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 664,
      title: '华港要评aaPL测试',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/275efa2b-60ad-4cf2-b752-dcfa34054e29blob.png',
      publishTime: 1629426016000,
      publisher: 'Jeff',
      source: '',
      digest: '华港要评aaPL测试华港要评aaPL测试',
      keywords: '["1"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 3,
      isOriginal: 1,
      newsType: 3,
      desc: '华港要评aaPL测试华港要评aaPL测试',
      keywordsList: ['1'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 662,
      title: '测试资讯全局搜索',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/1f0614bc-1d44-4285-93f5-56be3357b0e1blob.png',
      publishTime: 1629424602000,
      publisher: 'Jeff',
      source: '',
      digest: '测试资讯全局搜索测试资讯全局搜索测试资讯全局搜索',
      keywords: '["12"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 3,
      isOriginal: 1,
      newsType: 1,
      desc: '测试资讯全局搜索测试资讯全局搜索测试资讯全局搜索',
      keywordsList: ['12'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 661,
      title: 'AApl',
      image: '',
      publishTime: 1629357377000,
      publisher: 'Jeff',
      source: '',
      digest: 'AAplAAplAAplAApl',
      keywords: '["12"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 3,
      isOriginal: 1,
      newsType: 3,
      desc: 'AAplAAplAAplAApl',
      keywordsList: ['12'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 657,
      title: '123test TF',
      image: '',
      publishTime: 1628477871000,
      publisher: 'tongfong',
      source: '',
      digest: '',
      keywords: '["150"]',
      isOutside: 0,
      isMyself: 1,
      like: 0,
      share: 0,
      view: 1,
      objectType: 4,
      isOriginal: 1,
      newsType: 4,
      desc: '',
      keywordsList: ['150'],
      accountId: 10000108,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 656,
      title: '123',
      image: '',
      publishTime: 1628243024000,
      publisher: 'tongfong',
      source: '',
      digest: '123',
      keywords: '["1","6","12","21"]',
      isOutside: 0,
      isMyself: 1,
      like: 0,
      share: 0,
      view: 1,
      objectType: 4,
      isOriginal: 1,
      newsType: 1,
      desc: '123',
      keywordsList: ['1', '6', '12', '21'],
      accountId: 10000108,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 654,
      title: '国信证券：交通运输 —— 疫苗加速接种，物流个股上新',
      image:
        'http://wealth.fargowealth.com/images/b8dc1364-fbcf-48d1-95e7-18b63d20a241blob.png',
      publishTime: 1628156918000,
      publisher: '',
      source: '国信证券',
      digest: ' ',
      keywords: '["6","59","76","94"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 1,
      objectType: 7,
      isOriginal: 0,
      newsType: 6,
      desc: ' ',
      keywordsList: ['6', '59', '76', '94'],
      accountId: 0,
      isHomePage: 1,
      languageType: 1,
      tag: ['投行直击'],
      expireTime: 1622995200000,
      relatedStocks: [
        {
          id: null,
          institutionId: null,
          code: '2618',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'B',
        },
        {
          id: null,
          institutionId: null,
          code: '753',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'B',
        },
        {
          id: null,
          institutionId: null,
          code: '1919',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'B',
        },
        {
          id: null,
          institutionId: null,
          code: 'ZNH',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'B',
        },
        {
          id: null,
          institutionId: null,
          code: 'CEA',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'B',
        },
        {
          id: null,
          institutionId: null,
          code: 'ZTO',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'B',
        },
      ],
      isExpired: 0,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 653,
      title: 'testpic',
      image: '',
      publishTime: 1627964546000,
      publisher: 'Jeff',
      source: '',
      digest: '',
      keywords: '["1"]',
      isOutside: 1,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 3,
      objectType: 7,
      isOriginal: 1,
      newsType: 1,
      desc: '',
      keywordsList: ['1'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 652,
      title: '测试图片放大',
      image: '',
      publishTime: 1627964405000,
      publisher: 'Jeff',
      source: '',
      digest: '测试图片放大',
      keywords: '["1"]',
      isOutside: 1,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 3,
      objectType: 7,
      isOriginal: 1,
      newsType: 1,
      desc: '测试图片放大',
      keywordsList: ['1'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 651,
      title: '招商证券你真矬',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/08161b50-c3e5-458e-8936-a43e8b0175ecblob.png',
      publishTime: 1627640148000,
      publisher: 'Jeff',
      source: '',
      digest: '招商证券你真矬',
      keywords: '["1","6","21"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 5,
      objectType: 5,
      isOriginal: 1,
      newsType: 1,
      desc: '招商证券你真矬',
      keywordsList: ['1', '6', '21'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 649,
      title: '摇咿摇咿摇晕晕',
      image: '',
      publishTime: 1626938478000,
      publisher: 'Jeff',
      source: '',
      digest: '9898',
      keywords: '["9"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 4,
      objectType: 7,
      isOriginal: 1,
      newsType: 3,
      desc: '9898',
      keywordsList: ['9'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 648,
      title: 'rrrrrr',
      image: '',
      publishTime: 1626938428000,
      publisher: 'Jeff',
      source: '',
      digest: '',
      keywords: '["6"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 3,
      isOriginal: 1,
      newsType: 1,
      desc: '',
      keywordsList: ['6'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: 6087,
          institutionId: null,
          code: 'XAU',
          codeExchange: 'XAU',
          codeBloomberg: 'XAUUSD Curncy',
          nameEn: 'XAU',
          lastPrice: '',
          riseFallPer: '',
          name: 'XAU',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3088,
          institutionId: null,
          code: 'DDD',
          codeExchange: 'DDD',
          codeBloomberg: 'DDD SP Equity',
          nameEn: 'DDD SP Equity',
          lastPrice: '',
          riseFallPer: '',
          name: 'DDD SP Equity',
          market: 'SP',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 647,
      title: '5455454',
      image: '',
      publishTime: 1626938376000,
      publisher: 'Jeff',
      source: '',
      digest: '565656',
      keywords: '["21"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 7,
      isOriginal: 1,
      newsType: 1,
      desc: '565656',
      keywordsList: ['21'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 645,
      title: '【金马要评】国内教育政策未到转向时',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/f82070b2-6177-4a8e-b14c-299d03a32492blob.png',
      publishTime: 1626938078000,
      publisher: 'Jeff',
      source: '',
      digest: '',
      keywords: '["21"]',
      isOutside: 1,
      isMyself: 0,
      like: 0,
      share: 1,
      view: 9,
      objectType: 7,
      isOriginal: 1,
      newsType: 3,
      desc: '',
      keywordsList: ['21'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 644,
      title: 'Nomura: BLS unlikely to prevent dovish ECB guidance',
      image: '',
      publishTime: 1626937970000,
      publisher: 'Jeff',
      source: 'xxx',
      digest: '',
      keywords: '["6"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 7,
      isOriginal: 0,
      newsType: 8,
      desc: '',
      keywordsList: ['6'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 643,
      title: 'fdffdfdfdfd',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/aefad865-9081-4fda-94ff-5e782db008e7blob.png',
      publishTime: 1626752629000,
      publisher: 'Jeff',
      source: '',
      digest: 'dfddffd',
      keywords: '["149"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 3,
      objectType: 1,
      isOriginal: 1,
      newsType: 1,
      desc: 'dfddffd',
      keywordsList: ['149'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 642,
      title: '贵州茅台',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/65dc00db-0e23-4f44-a6fd-d0c79fc6d3ecblob.png',
      publishTime: 1625728281000,
      publisher: 'Jack',
      source: '',
      digest: '贵州茅台贵州茅台贵州茅台',
      keywords: '["1","6","14","74","148"]',
      isOutside: 0,
      isMyself: 0,
      like: 1,
      share: 2,
      view: 8,
      objectType: 1,
      isOriginal: 1,
      newsType: 1,
      desc: '贵州茅台贵州茅台贵州茅台',
      keywordsList: ['1', '6', '14', '74', '148'],
      accountId: 10000004,
      isHomePage: 1,
      languageType: 1,
      tag: ['热文'],
      expireTime: 1627660800000,
      relatedStocks: [],
      isExpired: 0,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 641,
      title: '金融街亮点英文Wall Street Highlights (CH)',
      image: '',
      publishTime: 1625650479000,
      publisher: 'Jeff',
      source: '',
      digest: 'Wall Street Highlights (CH)Wall Street Highlights (CH)',
      keywords: '["22"]',
      isOutside: 0,
      isMyself: 0,
      like: 1,
      share: 1,
      view: 10,
      objectType: 7,
      isOriginal: 1,
      newsType: 6,
      desc: 'Wall Street Highlights (CH)Wall Street Highlights (CH)',
      keywordsList: ['22'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 640,
      title: '盘前简报英文Morning Flash',
      image: '',
      publishTime: 1625650430000,
      publisher: 'Jeff',
      source: '',
      digest: 'Morning Flash',
      keywords: '["6"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 3,
      objectType: 7,
      isOriginal: 1,
      newsType: 1,
      desc: 'Morning Flash',
      keywordsList: ['6'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 639,
      title:
        '最近，VC很厌恶一个词，“明星项目”最近，VC很厌恶一个词，“明星项目”最近，VC很厌恶一个词，“明星项目”最近，VC很厌恶一个词，“明星项目”最近，VC很厌恶一个词，“明星项目”最近，VC很',
      image: '',
      publishTime: 1625556634000,
      publisher: 'Jeff',
      source: '',
      digest: '外行人看热闹，内行人看门道。',
      keywords: '["21"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 4,
      isOriginal: 1,
      newsType: 4,
      desc: '外行人看热闹，内行人看门道。',
      keywordsList: ['21'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: 6088,
          institutionId: null,
          code: 'lvmh',
          codeExchange: 'lvmh',
          codeBloomberg: 'lvmh',
          nameEn: 'lvmh',
          lastPrice: '',
          riseFallPer: '',
          name: 'lvmh',
          market: 'EU',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 21,
          institutionId: null,
          code: '3690',
          codeExchange: '03690',
          codeBloomberg: '3690 HK Equity',
          nameEn: 'Meituan Dianping',
          lastPrice: '',
          riseFallPer: '',
          name: '美团点评',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3073,
          institutionId: null,
          code: '9999',
          codeExchange: '09999',
          codeBloomberg: '9999 HK Equity',
          nameEn: 'Netease',
          lastPrice: '',
          riseFallPer: '',
          name: '网易',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 6,
          institutionId: null,
          code: 'BABA',
          codeExchange: 'BABA',
          codeBloomberg: 'BABA US Equity',
          nameEn: 'Alibaba Group Holding Ltd',
          lastPrice: '',
          riseFallPer: '',
          name: '阿里巴巴',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 40,
          institutionId: null,
          code: 'SE',
          codeExchange: 'SE',
          codeBloomberg: 'SE US Equity',
          nameEn: 'Sea Limited',
          lastPrice: '',
          riseFallPer: '',
          name: 'Sea Limited',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 39,
          institutionId: null,
          code: 'TSLA',
          codeExchange: 'TSLA',
          codeBloomberg: 'TSLA US Equity',
          nameEn: 'Tesla Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '特斯拉',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 10,
          institutionId: null,
          code: 'AAPL',
          codeExchange: 'AAPL',
          codeBloomberg: 'AAPL US Equity',
          nameEn: 'Apple Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '苹果',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 638,
      title: '私行视角',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/4fa80579-d7bd-4385-a1f2-d48822f3e188blob.png',
      publishTime: 1625485463000,
      publisher: 'Jeff',
      source: '',
      digest: '私行视角',
      keywords: '["14"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 1,
      objectType: 6,
      isOriginal: 1,
      newsType: 16,
      desc: '私行视角',
      keywordsList: ['14'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 637,
      title: '投行视角test',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/d7390cc8-a285-466c-aed6-629b8d9f58fdblob.png',
      publishTime: 1625466118000,
      publisher: 'Jeff',
      source: '',
      digest:
        '投行视角test投行视角test投行视角test投行视角test投行视角test投行视角test投行视角test投行视角test',
      keywords: '["14","25"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 1,
      objectType: 4,
      isOriginal: 1,
      newsType: 14,
      desc: '投行视角test投行视角test投行视角test投行视角test投行视角test投行视角test投行视角test投行视角test',
      keywordsList: ['14', '25'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 636,
      title: '市场快讯',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/e8e4c04e-33af-47c9-9343-e35c70fb65a1blob.png',
      publishTime: 1625466067000,
      publisher: 'Jeff',
      source: '',
      digest: '市场快讯市场快讯市场快讯市场快讯市场快讯市场快讯市场快讯',
      keywords: '["11","72"]',
      isOutside: 1,
      isMyself: 0,
      like: 1,
      share: 1,
      view: 3,
      objectType: 7,
      isOriginal: 1,
      newsType: 13,
      desc: '市场快讯市场快讯市场快讯市场快讯市场快讯市场快讯市场快讯',
      keywordsList: ['11', '72'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 2,
      tag: ['独家'],
      expireTime: null,
      relatedStocks: [
        {
          id: 3078,
          institutionId: null,
          code: '3347',
          codeExchange: '03347',
          codeBloomberg: '3347 HK Equity',
          nameEn: 'taigeyiyao',
          lastPrice: '',
          riseFallPer: '',
          name: '泰格医药',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3080,
          institutionId: null,
          code: '122',
          codeExchange: '00122',
          codeBloomberg: '122 HK Equity',
          nameEn: 'nong',
          lastPrice: '',
          riseFallPer: '',
          name: '农业主题',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3083,
          institutionId: null,
          code: 'MCT',
          codeExchange: 'MCT',
          codeBloomberg: 'MCT SP Equity',
          nameEn: 'MCT',
          lastPrice: '',
          riseFallPer: '',
          name: 'MCT SP Equity',
          market: 'SP',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 635,
      title: '债卷周报',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/6ac4ab76-8dc8-4853-a4a2-e7ef78b22b84blob.png',
      publishTime: 1625466015000,
      publisher: 'Jeff',
      source: '',
      digest: '债卷周报中文债卷周报债卷周报债卷周报债卷周报债卷周报债卷周报',
      keywords: '["16","27"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 4,
      isOriginal: 1,
      newsType: 10,
      desc: '债卷周报中文债卷周报债卷周报债卷周报债卷周报债卷周报债卷周报',
      keywordsList: ['16', '27'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 634,
      title: 'wall英文',
      image: '',
      publishTime: 1625465959000,
      publisher: 'Jeff',
      source: '',
      digest: 'wall英文wall英文wall英文wall英文wall英文',
      keywords: '["13","14","15"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 4,
      isOriginal: 1,
      newsType: 8,
      desc: 'wall英文wall英文wall英文wall英文wall英文',
      keywordsList: ['13', '14', '15'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 633,
      title:
        '资金动向中文资金动向资金动向资金动向资金动向资金动向资金动向资金动向资金动向资金动向',
      image: '',
      publishTime: 1625465917000,
      publisher: 'Jeff',
      source: '',
      digest: '',
      keywords: '["14","25"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 4,
      isOriginal: 1,
      newsType: 7,
      desc: '',
      keywordsList: ['14', '25'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: 84,
          institutionId: null,
          code: 'PG',
          codeExchange: 'PG',
          codeBloomberg: 'PG US Equity',
          nameEn: 'Procter & Gamble Co/The',
          lastPrice: '',
          riseFallPer: '',
          name: '宝洁',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 115,
          institutionId: null,
          code: 'PFE',
          codeExchange: 'PFE',
          codeBloomberg: 'PFE US Equity',
          nameEn: 'Pfizer Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '辉瑞制药',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 156,
          institutionId: null,
          code: 'PM',
          codeExchange: 'PM',
          codeBloomberg: 'PM US Equity',
          nameEn: 'Philip Morris International In',
          lastPrice: '',
          riseFallPer: '',
          name: '菲利普莫里斯国际集团公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 162,
          institutionId: null,
          code: 'PYPL',
          codeExchange: 'PYPL',
          codeBloomberg: 'PYPL US Equity',
          nameEn: 'PayPal Holdings Inc',
          lastPrice: '',
          riseFallPer: '',
          name: 'Paypal控股股份有限公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 15,
          institutionId: null,
          code: 'FB',
          codeExchange: 'FB',
          codeBloomberg: 'FB US Equity',
          nameEn: 'Facebook Inc',
          lastPrice: '',
          riseFallPer: '',
          name: 'Facebook',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 209,
          institutionId: null,
          code: 'FIS',
          codeExchange: 'FIS',
          codeBloomberg: 'FIS US Equity',
          nameEn: 'Fidelity National Information',
          lastPrice: '',
          riseFallPer: '',
          name: '繁德信息技术有限公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 222,
          institutionId: null,
          code: 'FISV',
          codeExchange: 'FISV',
          codeBloomberg: 'FISV US Equity',
          nameEn: 'Fiserv Inc',
          lastPrice: '',
          riseFallPer: '',
          name: 'Fiserv公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 632,
      title:
        '金融街亮点无摘要英文金融街亮点无摘要英文金融街亮点无摘要英文金融街亮点无摘要英文金融街亮点无摘要英文金融街亮点无摘要英文金融街亮点无摘要英文金融街亮点无摘要英文金融街亮点无摘要英文金融街亮点无',
      image: '',
      publishTime: 1625465804000,
      publisher: 'Jeff',
      source: '',
      digest: '',
      keywords: '["11","16"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 1,
      objectType: 4,
      isOriginal: 1,
      newsType: 6,
      desc: '',
      keywordsList: ['11', '16'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 631,
      title: '金融街亮点金中文无摘要',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/47fe90cc-1319-4ee2-88ee-a58813f7190fblob.png',
      publishTime: 1625465455000,
      publisher: 'Jeff',
      source: '',
      digest:
        '金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点',
      keywords: '["9"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 1,
      objectType: 4,
      isOriginal: 1,
      newsType: 6,
      desc: '金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点金融街亮点',
      keywordsList: ['9'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 630,
      title:
        '银行信息英文 银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文',
      image: '',
      publishTime: 1625465226000,
      publisher: 'Jeff',
      source: '',
      digest:
        '银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文',
      keywords: '["11"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 4,
      isOriginal: 1,
      newsType: 5,
      desc: '银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文银行信息英文',
      keywordsList: ['11'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: 11,
          institutionId: null,
          code: 'GOOG',
          codeExchange: 'GOOG',
          codeBloomberg: 'GOOG US Equity',
          nameEn: 'Google',
          lastPrice: '',
          riseFallPer: '',
          name: '谷歌',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 10,
          institutionId: null,
          code: 'AAPL',
          codeExchange: 'AAPL',
          codeBloomberg: 'AAPL US Equity',
          nameEn: 'Apple Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '苹果',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 9,
          institutionId: null,
          code: 'MSFT',
          codeExchange: 'MSFT',
          codeBloomberg: 'MSFT US Equity',
          nameEn: 'Microsoft',
          lastPrice: '',
          riseFallPer: '',
          name: '微软',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 8,
          institutionId: null,
          code: 'NFLX',
          codeExchange: 'NFLX',
          codeBloomberg: 'NFLX US Equity',
          nameEn: 'Netflix Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '奈飞',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 7,
          institutionId: null,
          code: 'AMZN',
          codeExchange: 'AMZN',
          codeBloomberg: 'AMZN US Equity',
          nameEn: 'Amazon.com Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '亚马逊',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 6,
          institutionId: null,
          code: 'BABA',
          codeExchange: 'BABA',
          codeBloomberg: 'BABA US Equity',
          nameEn: 'Alibaba Group Holding Ltd',
          lastPrice: '',
          riseFallPer: '',
          name: '阿里巴巴',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 34,
          institutionId: null,
          code: 'SQ',
          codeExchange: 'SQ',
          codeBloomberg: 'SQ US Equity',
          nameEn: 'Square Inc',
          lastPrice: '',
          riseFallPer: '',
          name: 'Square',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 35,
          institutionId: null,
          code: 'QD',
          codeExchange: 'QD',
          codeBloomberg: 'QD US Equity',
          nameEn: 'Qudian Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '趣店',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 33,
          institutionId: null,
          code: 'AMD',
          codeExchange: 'AMD',
          codeBloomberg: 'AMD US Equity',
          nameEn: 'Advanced Micro Decices Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '美国超微公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3067,
          institutionId: null,
          code: 'ASML',
          codeExchange: 'ASML',
          codeBloomberg: 'ASML US Equity',
          nameEn: 'ASML Holding',
          lastPrice: '',
          riseFallPer: '',
          name: '阿麦斯公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 629,
      title:
        'PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/1946548e-4fa8-4061-aa76-091526a87e9fblob.png',
      publishTime: 1625459772000,
      publisher: 'Jeff',
      source: '',
      digest:
        'PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品',
      keywords: '["13","14"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 3,
      objectType: 6,
      isOriginal: 1,
      newsType: 16,
      desc: 'PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品PB资讯有头像有摘要有相关产品',
      keywordsList: ['13', '14'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: 3067,
          institutionId: null,
          code: 'ASML',
          codeExchange: 'ASML',
          codeBloomberg: 'ASML US Equity',
          nameEn: 'ASML Holding',
          lastPrice: '',
          riseFallPer: '',
          name: '阿麦斯公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 33,
          institutionId: null,
          code: 'AMD',
          codeExchange: 'AMD',
          codeBloomberg: 'AMD US Equity',
          nameEn: 'Advanced Micro Decices Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '美国超微公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 35,
          institutionId: null,
          code: 'QD',
          codeExchange: 'QD',
          codeBloomberg: 'QD US Equity',
          nameEn: 'Qudian Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '趣店',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 34,
          institutionId: null,
          code: 'SQ',
          codeExchange: 'SQ',
          codeBloomberg: 'SQ US Equity',
          nameEn: 'Square Inc',
          lastPrice: '',
          riseFallPer: '',
          name: 'Square',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 6,
          institutionId: null,
          code: 'BABA',
          codeExchange: 'BABA',
          codeBloomberg: 'BABA US Equity',
          nameEn: 'Alibaba Group Holding Ltd',
          lastPrice: '',
          riseFallPer: '',
          name: '阿里巴巴',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 9,
          institutionId: null,
          code: 'MSFT',
          codeExchange: 'MSFT',
          codeBloomberg: 'MSFT US Equity',
          nameEn: 'Microsoft',
          lastPrice: '',
          riseFallPer: '',
          name: '微软',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 8,
          institutionId: null,
          code: 'NFLX',
          codeExchange: 'NFLX',
          codeBloomberg: 'NFLX US Equity',
          nameEn: 'Netflix Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '奈飞',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 10,
          institutionId: null,
          code: 'AAPL',
          codeExchange: 'AAPL',
          codeBloomberg: 'AAPL US Equity',
          nameEn: 'Apple Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '苹果',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 11,
          institutionId: null,
          code: 'GOOG',
          codeExchange: 'GOOG',
          codeBloomberg: 'GOOG US Equity',
          nameEn: 'Google',
          lastPrice: '',
          riseFallPer: '',
          name: '谷歌',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 628,
      title:
        '结构化产品中文有摘要结构化产品结构化产品结构化产品结构化产品结构化产品',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/530b852c-d037-408f-a05d-fb8ac5a93e4ablob.png',
      publishTime: 1625459679000,
      publisher: 'Jeff',
      source: '',
      digest:
        '结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品',
      keywords: '["12","13"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 4,
      isOriginal: 1,
      newsType: 4,
      desc: '结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品结构化产品',
      keywordsList: ['12', '13'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: 3071,
          institutionId: null,
          code: '763',
          codeExchange: '00763',
          codeBloomberg: '763 HK Equity',
          nameEn: 'Zhongxin',
          lastPrice: '',
          riseFallPer: '',
          name: '中兴通讯',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3072,
          institutionId: null,
          code: 'BLCT',
          codeExchange: 'BLCT',
          codeBloomberg: 'BLCT US Equity',
          nameEn: 'Blued',
          lastPrice: '',
          riseFallPer: '',
          name: '蓝城兄弟',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3073,
          institutionId: null,
          code: '9999',
          codeExchange: '09999',
          codeBloomberg: '9999 HK Equity',
          nameEn: 'Netease',
          lastPrice: '',
          riseFallPer: '',
          name: '网易',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3074,
          institutionId: null,
          code: '9988',
          codeExchange: '09988',
          codeBloomberg: '9988 HK Equity',
          nameEn: 'Alibaba',
          lastPrice: '',
          riseFallPer: '',
          name: '阿里巴巴',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3075,
          institutionId: null,
          code: 'PCRFY',
          codeExchange: 'PCRFY',
          codeBloomberg: 'PCRFY JP Equity',
          nameEn: 'Panasonic',
          lastPrice: '',
          riseFallPer: '',
          name: '松下电器',
          market: 'JT',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3076,
          institutionId: null,
          code: 'VOW',
          codeExchange: 'VOW',
          codeBloomberg: 'VOW GY Equity',
          nameEn: 'VOLKSWAGEN AG',
          lastPrice: '',
          riseFallPer: '',
          name: 'VOLKSWAGEN AG',
          market: 'GY',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3067,
          institutionId: null,
          code: 'ASML',
          codeExchange: 'ASML',
          codeBloomberg: 'ASML US Equity',
          nameEn: 'ASML Holding',
          lastPrice: '',
          riseFallPer: '',
          name: '阿麦斯公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 33,
          institutionId: null,
          code: 'AMD',
          codeExchange: 'AMD',
          codeBloomberg: 'AMD US Equity',
          nameEn: 'Advanced Micro Decices Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '美国超微公司',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 35,
          institutionId: null,
          code: 'QD',
          codeExchange: 'QD',
          codeBloomberg: 'QD US Equity',
          nameEn: 'Qudian Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '趣店',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 10,
          institutionId: null,
          code: 'AAPL',
          codeExchange: 'AAPL',
          codeBloomberg: 'AAPL US Equity',
          nameEn: 'Apple Inc',
          lastPrice: '',
          riseFallPer: '',
          name: '苹果',
          market: 'US',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 627,
      title:
        '金马要评英文面无摘要金马要评无封面无摘要金马要评无封面无摘要金马要评无封面无摘要金马要评无封面无摘要金马要评无封面无摘要金马要评无封面无摘要金马要评无封面无摘要金马要评无封面无摘要金马要评无封',
      image: '',
      publishTime: 1625459563000,
      publisher: 'Jeff',
      source: '',
      digest: '',
      keywords: '["11"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 1,
      objectType: 4,
      isOriginal: 1,
      newsType: 3,
      desc: '',
      keywordsList: ['11'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 626,
      title:
        '周度脉搏英文无摘要无相关数据15% p.a. FCN on Bitcoin Thematic Basket (50% Strike)15% p.a. FCN on Bitcoin Themat',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/1b0bf930-392c-4332-ba6b-bf2798de3f9bblob.png',
      publishTime: 1625458840000,
      publisher: 'Jeff',
      source: '',
      digest: '',
      keywords: '["16","17"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 4,
      isOriginal: 1,
      newsType: 2,
      desc: '',
      keywordsList: ['16', '17'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 625,
      title:
        '中文版的盘前简报且有摘要中文版的盘前简报且有封面中文版的盘前简报且有封面中文版的盘前简报且有封面中文版的盘前简报且有封面中文版的盘前简报且有封面中文版的盘前简报且有封面中文版的盘前简报且有封面',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/e26eaac5-2686-47aa-a2ff-884c97330547blob.png',
      publishTime: 1625458401000,
      publisher: 'Jeff',
      source: '',
      digest: '中文版的盘前简报且有摘要',
      keywords: '["9","13"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 2,
      objectType: 4,
      isOriginal: 1,
      newsType: 1,
      desc: '中文版的盘前简报且有摘要',
      keywordsList: ['9', '13'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: 3078,
          institutionId: null,
          code: '3347',
          codeExchange: '03347',
          codeBloomberg: '3347 HK Equity',
          nameEn: 'taigeyiyao',
          lastPrice: '',
          riseFallPer: '',
          name: '泰格医药',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3074,
          institutionId: null,
          code: '9988',
          codeExchange: '09988',
          codeBloomberg: '9988 HK Equity',
          nameEn: 'Alibaba',
          lastPrice: '',
          riseFallPer: '',
          name: '阿里巴巴',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
        {
          id: 3073,
          institutionId: null,
          code: '9999',
          codeExchange: '09999',
          codeBloomberg: '9999 HK Equity',
          nameEn: 'Netease',
          lastPrice: '',
          riseFallPer: '',
          name: '网易',
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: null,
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 624,
      title: '金马要评IOS推送1',
      image: '',
      publishTime: 1624586890000,
      publisher: 'Jeff',
      source: '',
      digest: '金马要评IOS推送金马要评IOS推送',
      keywords: '["12"]',
      isOutside: 1,
      isMyself: 0,
      like: 0,
      share: 1,
      view: 7,
      objectType: 1,
      isOriginal: 1,
      newsType: 3,
      desc: '金马要评IOS推送金马要评IOS推送',
      keywordsList: ['12'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 622,
      title: '标题-另类投资-有来源',
      image: '',
      publishTime: 1624438172000,
      publisher: 'Jeff',
      source: '华夏银行',
      digest: '摘要-另类投资-有来源',
      keywords: '["11"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 5,
      objectType: 6,
      isOriginal: 0,
      newsType: 16,
      desc: '摘要-另类投资-有来源',
      keywordsList: ['11'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 621,
      title: '标题-大宗商品-有来源',
      image: '',
      publishTime: 1624438097000,
      publisher: 'Jeff',
      source: '建设银行',
      digest: '摘要-大宗商品-有来源',
      keywords: '["9"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 6,
      isOriginal: 0,
      newsType: 16,
      desc: '摘要-大宗商品-有来源',
      keywordsList: ['9'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 620,
      title: '标题-外汇-有来源',
      image: '',
      publishTime: 1624438050000,
      publisher: 'Jeff',
      source: '招商银行',
      digest: '摘要-外汇-有来源',
      keywords: '["8"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 1,
      objectType: 6,
      isOriginal: 0,
      newsType: 16,
      desc: '摘要-外汇-有来源',
      keywordsList: ['8'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 619,
      title: '债券-标题-有来源',
      image: '',
      publishTime: 1624437992000,
      publisher: 'Jeff',
      source: '中国银行',
      digest: '债券-摘要-有来源',
      keywords: '["7"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 6,
      isOriginal: 0,
      newsType: 16,
      desc: '债券-摘要-有来源',
      keywordsList: ['7'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 618,
      title: '股票-有来源-标题',
      image: '',
      publishTime: 1624421718000,
      publisher: 'Jeff',
      source: '工商银行',
      digest: '股票-有来源-摘要',
      keywords: '["6"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 6,
      isOriginal: 0,
      newsType: 16,
      desc: '股票-有来源-摘要',
      keywordsList: ['6'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 616,
      title: '银行信息测试',
      image: '',
      publishTime: 1623925319000,
      publisher: 'Jeff',
      source: '',
      digest: '银行信息测试银行信息测试',
      keywords: '["13"]',
      isOutside: 0,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 1,
      objectType: 1,
      isOriginal: 1,
      newsType: 5,
      desc: '银行信息测试银行信息测试',
      keywordsList: ['13'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 615,
      title: '刚刚，神舟十二号与天和核心舱完成自主快速交会对接',
      image:
        'https://u.fargo-crm.easyview.xyz:8443/images/32a019e7-25c5-482e-a973-e98d8ddeee3bblob.png',
      publishTime: 1623925227000,
      publisher: 'Jeff',
      source: '',
      digest: '北京日报客户端',
      keywords: '["1","6"]',
      isOutside: 1,
      isMyself: 0,
      like: 0,
      share: 1,
      view: 7,
      objectType: 1,
      isOriginal: 1,
      newsType: 1,
      desc: '北京日报客户端',
      keywordsList: ['1', '6'],
      accountId: 10000005,
      isHomePage: 0,
      languageType: 1,
      tag: [],
      expireTime: null,
      relatedStocks: [],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 614,
      title: '2021/7/17-15:48',
      image:
        'http://wealth.fargowealth.com/images/e9113be1-c27e-4a12-86a4-0ba2b750677dblob.png',
      publishTime: 1623916152000,
      publisher: '',
      source: 'kuixiang.liao',
      digest: ' ',
      keywords: '["115","116","130"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 6,
      isOriginal: 0,
      newsType: 8,
      desc: ' ',
      keywordsList: ['115', '116', '130'],
      accountId: 0,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: null,
          institutionId: null,
          code: '981',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
        {
          id: null,
          institutionId: null,
          code: '3690',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
        {
          id: null,
          institutionId: null,
          code: '700',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 613,
      title: '2021/7/17-15:21',
      image:
        'http://wealth.fargowealth.com/images/38b003aa-b03b-478b-8673-104b82321debblob.png',
      publishTime: 1623914523000,
      publisher: '',
      source: 'kuixiang.liao',
      digest: ' ',
      keywords: '["115","116","130"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 6,
      isOriginal: 0,
      newsType: 8,
      desc: ' ',
      keywordsList: ['115', '116', '130'],
      accountId: 0,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: null,
          institutionId: null,
          code: '981',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
        {
          id: null,
          institutionId: null,
          code: '3690',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
        {
          id: null,
          institutionId: null,
          code: '700',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 612,
      title: '2021/7/17-15:08',
      image:
        'http://wealth.fargowealth.com/images/4e7e81f6-469f-4465-bf99-291a84140eafblob.png',
      publishTime: 1623914278000,
      publisher: '',
      source: 'kuixiang.liao',
      digest: ' ',
      keywords: '["115","116","130"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 6,
      isOriginal: 0,
      newsType: 8,
      desc: ' ',
      keywordsList: ['115', '116', '130'],
      accountId: 0,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: null,
          institutionId: null,
          code: '981',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
        {
          id: null,
          institutionId: null,
          code: '3690',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
        {
          id: null,
          institutionId: null,
          code: '700',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 611,
      title: '2021/7/17-14:34',
      image:
        'http://wealth.fargowealth.com/images/59e3f2e4-3868-440c-aef8-67f32676e093blob.png',
      publishTime: 1623911831000,
      publisher: '',
      source: 'kuixiang.liao',
      digest: ' ',
      keywords: '["115","116","130"]',
      isOutside: 0,
      isMyself: 0,
      like: null,
      share: null,
      view: null,
      objectType: 6,
      isOriginal: 0,
      newsType: 8,
      desc: ' ',
      keywordsList: ['115', '116', '130'],
      accountId: 0,
      isHomePage: 0,
      languageType: 2,
      tag: [],
      expireTime: null,
      relatedStocks: [
        {
          id: null,
          institutionId: null,
          code: '981',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
        {
          id: null,
          institutionId: null,
          code: '3690',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
        {
          id: null,
          institutionId: null,
          code: '700',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'S',
        },
      ],
      isExpired: null,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 610,
      title:
        '【市场动态】美国法院撤销美国投资者购买或持有小米(1810.HK)限制20210610-13:53',
      image:
        'http://wealth.fargowealth.com/images/ac02dd2e-8b5d-4f7e-a9c6-21f11a0155e2blob.png',
      publishTime: 1623840655000,
      publisher: '',
      source: 'CIO Office',
      digest: ' ',
      keywords: '["1","3","6","12","15","74","119"]',
      isOutside: 1,
      isMyself: 0,
      like: 0,
      share: 2,
      view: 9,
      objectType: 7,
      isOriginal: 0,
      newsType: 7,
      desc: ' ',
      keywordsList: ['1', '3', '6', '12', '15', '74', '119'],
      accountId: 0,
      isHomePage: 1,
      languageType: 1,
      tag: ['热文'],
      expireTime: 1623840655000,
      relatedStocks: [
        {
          id: null,
          institutionId: null,
          code: '1810',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'B',
        },
      ],
      isExpired: 0,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
    {
      id: 609,
      title: '【市场动态】太平洋航运（2343.HK）创历史新高',
      image:
        'http://wealth.fargowealth.com/images/4a804c86-8feb-42ae-99c9-9615b845d8ffblob.png',
      publishTime: 1623838272000,
      publisher: '',
      source: 'CIO Office',
      digest: ' ',
      keywords: '["6","74","94","119","147"]',
      isOutside: 1,
      isMyself: 0,
      like: 0,
      share: 0,
      view: 1,
      objectType: 7,
      isOriginal: 0,
      newsType: 7,
      desc: ' ',
      keywordsList: ['6', '74', '94', '119', '147'],
      accountId: 0,
      isHomePage: 1,
      languageType: 1,
      tag: ['热文'],
      expireTime: 1623838272000,
      relatedStocks: [
        {
          id: null,
          institutionId: null,
          code: '2343',
          codeExchange: null,
          codeBloomberg: null,
          nameEn: null,
          lastPrice: '',
          riseFallPer: '',
          name: null,
          market: 'HK',
          quoteCurrency: null,
          desc: null,
          type: null,
          status: null,
          topFlag: null,
          createTime: null,
          createUser: null,
          uptime: null,
          rating: 'B',
        },
      ],
      isExpired: 0,
      featuredStocks: null,
      increaseStocks: null,
      decreaseStocks: null,
      featuredBonds: null,
      increaseBond: null,
      decreaseBond: null,
      weeklyBonds: null,
      relations: null,
      privateEquities: [],
    },
  ],
  resultMap: null,
}
